### ISSUE TITLE
Add a way to read passwords

### ISSUE THREAD

**Issue by Asmod4n** [antirez/linenoise#125]
Would be cool if linenoise could disable echoing etc so passwords aren't written to the ternimal.

**Comment by OlliV** [comment]
Reading passwords securely requires more than that. Usually you want to ensure no one else is reading the input and that you are really connected to a terminal etc.

**Comment by Asmod4n** [comment]
The macOS Terminal has a special mode for that, which you have to enable.
The bundled read -s (from bash or zsh) displays a "lock" icon when that secure input mode is enabled. Same goes for getpass from unistd.h.

But when i copy that code that icon doesn't get displayed :/

**Comment by xeruf** [comment]
why is this closed?
