### ISSUE TITLE
Use linenoise-ng instead?

### ISSUE THREAD

**Issue by pureconfig** [antirez/linenoise#132]
https://github.com/arangodb/linenoise-ng supports Windows.

Is it supposed to supersede this linenoise repo?

**Comment by Sonophoto** [comment]
Why did you open a new issue???

**Comment by pureconfig** [comment]
Because that's a different issue

**Comment by antirez** [comment]
Hello, there are a few things I would add like UTF8 minimal support (discussed in another issue), however to add support for Windows is currently not the goal, given that there is a fork that handles it. Remember that Linenoise design is specifically focusing simplicity... So as long they are small self-contained additions that are very useful, I'll add them, but if I see complex and/or C++ code, it's unlikely I'll merge. It's great that @fceller is providing an alternative, but linenoise-ng cannot be considered a set of patches on top of linenoise, more a spin-off project that changed language, goals, and so forth.

**Comment by Sonophoto** [comment]
@antirez (FYI) 

There are two other modified versions of linenoise:

@yhirose 's cpp version includes UTF-8 support, and windows:
https://github.com/yhirose/cpp-linenoise

@sonophoto 's version is C, POSIX and supports UTF-8 and ANSI color.
https://github.com/Sonophoto/linenoise

I think we both watch your bug fixes and back-port them as appropriate. I think my last change was the history file permission issue.
