### ISSUE TITLE
Linenoise does not work with IntelliJ debug console

### ISSUE THREAD

**Issue by mcfriend99** [antirez/linenoise#203]
Hi,

When switching my application from `libreadline` to `linenoise`, I noticed that I can no longer debug my application from the IntelliJ console (terminal works alright). The line input just doesn't end, and newline just goes to the next line and I can just keep typing.

I would have opened this issue at IntelliJ, but all others I have tried (`libedit`, `tecla`, `replxx` majorly) works fine with IntelliJ debug console. What could be the problem?? Can this be fixes??

It would be nice to be able to debug my application from my IDE.

**Comment by mfxiaosheng** [comment]
static int isUnsupportedTerm(void)  You can look at this function

**Comment by mcfriend99** [comment]
I looked at it and it's evaluating to supported.

**Comment by mcfriend99** [comment]
I resolved this by setting environment variable `TERM` to "dummy".
